spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/travelfreemanage?characterEncoding=utf-8
    username: root
    password: 229826

  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

server:
  port: 8098

# 在现有配置中添加
weather:
  api:
    url: "https://api.heweather.net/s6/weather"
    key: "2f5e688e80db4365b66b114b8f0f70b1"