spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/travelfreemanage?characterEncoding=utf-8
    username: root
    password: 229826

  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: org.example.entity
server:
  port: 8098

# 天气API的ID与KEY
weather:
  api:
    url: "https://cn.apihz.cn/api/tianqi/tqyb.php"
    id: "88888888"
    key: "88888888"

    